window.RANKING_DADOS = {
  titulo: "TOP POR PACOTES/MINUTOS",
  tituloAlfabetico: "PRODUTIVIDADE AM",
  tituloPerformance: "TOP POR PACOTES/MINUTOS",
  tituloVolumoso: "PERFORMANCE VOLUMOSO",
  tituloGestor: "PERFORMANCE POR GESTOR",
  tituloHora: "GESTÃO HORA A HORA",
  criterioVerde: 4.5,
  criterioAmarelo: 4.0,
  gestores: {},
  horas: {},
  horaLinhas: [],
  linhas: [
    { representante: "Tamires Pereira Da Silva", pacotesMinuto: 5.92, tempoEfetivo: "02:52:59", unidades: 1024 },
    { representante: "Joao Victor Santos Chuva De Andrade", pacotesMinuto: 5.74, tempoEfetivo: "03:35:32", unidades: 1237 },
    { representante: "Julia Da Silva Reis Dos Santos", pacotesMinuto: 5.67, tempoEfetivo: "03:43:00", unidades: 1265 },
    { representante: "Andrew Lucca Vieira", pacotesMinuto: 5.63, tempoEfetivo: "03:02:34", unidades: 1027 },
    { representante: "Maria Eduarda Florindo", pacotesMinuto: 5.31, tempoEfetivo: "02:37:30", unidades: 972 },
    { representante: "Andreia Aparecida Lourenco", pacotesMinuto: 5.27, tempoEfetivo: "03:15:09", unidades: 1157 },
    { representante: "Danilo Pesqueira De Carvalho De Carvalho", pacotesMinuto: 5.26, tempoEfetivo: "03:06:36", unidades: 1005 },
    { representante: "Carlos Eduardo Mariano Da Silva", pacotesMinuto: 5.23, tempoEfetivo: "03:24:23", unidades: 754 },
    { representante: "Thais Pesqueira Gomes", pacotesMinuto: 5.23, tempoEfetivo: "03:45:53", unidades: 946 },
    { representante: "Silmara Farias Dos Santos", pacotesMinuto: 5.10, tempoEfetivo: "03:00:36", unidades: 878 },
    { representante: "Debora Vitoria Adel Hernandez", pacotesMinuto: 4.85, tempoEfetivo: "03:14:07", unidades: 949 },
    { representante: "Aisiane Cosmira Aranha", pacotesMinuto: 4.79, tempoEfetivo: "03:39:22", unidades: 1008 },
    { representante: "Simone Porto Alves", pacotesMinuto: 4.71, tempoEfetivo: "02:47:51", unidades: 921 },
    { representante: "Ana Claudia Valerio De Lima", pacotesMinuto: 4.64, tempoEfetivo: "03:45:31", unidades: 754 },
    { representante: "Gabriel Pastori Mendes De Araujo", pacotesMinuto: 4.64, tempoEfetivo: "03:22:18", unidades: 884 },
    { representante: "Annevse Camila De Assis Nascimento", pacotesMinuto: 4.52, tempoEfetivo: "02:48:32", unidades: 878 },
    { representante: "Mariana Amarante De Sousa", pacotesMinuto: 4.46, tempoEfetivo: "03:17:14", unidades: 949 },
    { representante: "Jose De Paula Arimar", pacotesMinuto: 4.43, tempoEfetivo: "03:31:18", unidades: 1008 },
    { representante: "Alessandra Cristina Cruz Silva", pacotesMinuto: 4.40, tempoEfetivo: "03:36:40", unidades: 993 },
    { representante: "Mariane Da Silva Antonio", pacotesMinuto: 4.39, tempoEfetivo: "03:08:15", unidades: 779 },
    { representante: "Stefanie Souza Da Silva", pacotesMinuto: 4.31, tempoEfetivo: "03:07:00", unidades: 1031 },
    { representante: "Maria Luiza Lima Santos", pacotesMinuto: 4.28, tempoEfetivo: "03:31:55", unidades: 1109 },
    { representante: "Reinaldo Braz Filho", pacotesMinuto: 4.14, tempoEfetivo: "03:27:14", unidades: 623 },
    { representante: "Larissa Souza De Alencar", pacotesMinuto: 4.06, tempoEfetivo: "03:22:18", unidades: 834 },
    { representante: "Launa Lima Da Costa", pacotesMinuto: 4.06, tempoEfetivo: "03:00:36", unidades: 831 },
    { representante: "Vinicius Santos De Oliveira", pacotesMinuto: 3.91, tempoEfetivo: "03:06:03", unidades: 877 },
    { representante: "Mayara Teixeira Santos", pacotesMinuto: 3.89, tempoEfetivo: "02:48:32", unidades: 619 },
    { representante: "Vitoria Loys Rodrigues", pacotesMinuto: 3.87, tempoEfetivo: "03:01:49", unidades: 821 },
    { representante: "Angelica Oliveira Durval", pacotesMinuto: 3.87, tempoEfetivo: "03:26:22", unidades: 921 },
    { representante: "Leonora Silva Costa", pacotesMinuto: 3.82, tempoEfetivo: "03:26:22", unidades: 683 },
    { representante: "Rodrigo Henrique", pacotesMinuto: 3.67, tempoEfetivo: "03:28:22", unidades: 659 },
    { representante: "Rodrigola Henrique", pacotesMinuto: 3.26, tempoEfetivo: "03:54:53", unidades: 586 }
  ]
};
